project_id = "dblnjqfkfgwtlsscncml"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = true

[functions.cloudflare-dns]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.vps-management]
verify_jwt = false

[functions.tunnel-management]
verify_jwt = false

[functions.cloudflare-import]
verify_jwt = false

[functions.domain-health]
verify_jwt = false

[functions.cloudflare-nameservers]
verify_jwt = false